修改dockerfile

diff --git a/parent/lifpay-gateway/Dockerfile b/parent/lifpay-gateway/Dockerfile
--- a/parent/lifpay-gateway/Dockerfile
+++ b/parent/lifpay-gateway/Dockerfile
@@ -2,7 +2,10 @@ FROM adoptopenjdk/openjdk8:jdk8u362-b09
 WORKDIR /app
 
 COPY target/*.jar /app/
-RUN mv /app/*SNAPSHOT.jar /app/app.jar
+RUN if [ -z "$(ls /app/*.jar 2>/dev/null)"  ]; then \
+    echo "ERROR: 未找到 Jar 包！"; \
+    exit 1; \
+    fi
 
 ENV TZ=Asia/Shanghai
 ENV JAVA_OPTS="-Dfile.encoding=utf8 -Djava.security.egd=file:/dev/.urandom"
@@ -10,4 +13,4 @@ ENV PARAMS="--server.port=9001 --spring.profiles.active=test --spring.cloud.naco
 
 EXPOSE 9001
 
-ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app/jar $PARAMS"]
+ENTRYPOINT ["sh","-c","java $JAVA_OPTS -jar /app/app.jar $PARAMS"]
